version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password!123" 
      ACCEPT_EULA: "Y"
